package org.joshdurbin.domain.enums

enum Maneuver {

  TURNING_ON_RED,
  STRAIGHT_AHEAD,
  STARTING_IN_TRAFFIC,
  ENTER_FROM_DRIVE_ALLEY,
  TURNING_RIGHT,
  CHANGING_LANES,
  TURNING_LEFT,
  BACKING,
  UNKNOWN,
  SLOW_STOP_IN_TRAFFIC,
  ENTERING_TRAFFIC_LANE_FR,
  OTHER,
  SLOW_STOP_LOAD_UNLOAD,
  PASSING_OVERTAKING,
  U_TURN,
  MERGING,
  SLOW_STOP_RIGHT_TURN,
  SLOW_STOP_LEFT_TURN,
  SKIDDING_CONTROL_LOSS,
  DRIVING_WRONG_WAY,
  LEAVING_TRAFFIC_LANE_TO,
  NEGOTIATING_A_CURVE,
  AVOIDING_VEHICLE_OBJECTS,
  PARKED_IN_TRAFFIC_LANE
}
