package org.joshdurbin.domain.enums

enum TrafficControl {

  TRAFFIC_SIGNAL,
  NO_CONTROLS,
  STOP_SIGN_FLASHER,
  LANE_USE_MARKING,
  YIELD,
  UNKNOWN,
  OTHER_WARNING_SIGN,
  OTHER,
  OTHER_REGULATORY_SIGN,
  NO_PASSING,
  POLICE_FLAGMAN,
  RR_CROSSING_GATE,
  DELINEATORS,
  SCHOOL_ZONE
}
