package org.joshdurbin.domain.enums

enum VehicleSpecification {

  PERSONAL,
  COMMERCIAL_SINGLE_UNIT,
  TAXI_FOR_HIRE,
  UNKNOWN,
  CTA,
  NOT_IN_USE,
  OTHER,
  CONSTRUCTION_MAINTENANCE,
  POLICE,
  TOW_TRUCK,
  AMBULANCE,
  SCHOOL_BUS,
  OTHER_TRANSIT,
  MASS_TRANSIT,
  STATE_OWNED,
  COMMERCIAL_MULTI_UNIT,
  DRIVER_EDUCATION,
  FIRE,
  HOUSE_TRAILER
}
