package org.joshdurbin.domain.enums

enum VehicleType {

  VAN_MINI_VAN,
  PASSENGER,
  SUV,
  TRUCK_SINGLE_UNIT,
  PICKUP,
  BUS_OVER_15_PASSENGERS,
  UNKNOWN,
  OTHER,
  TRACTOR_WITH_SEMI_TRAILER,
  MOTOR_DRIVEN_CYCLE,
  MOTORCYCLE_OVER_150CC,
  BUS_UP_TO_15_PASSENGERS,
  OTHER_VEHICLE_WITH_TRAILER,
  ATV,
  TRACTOR_WITHOUT_SEMI_TRAILER
}
